preview = true
line-length = 180

[lint]
select = [
   "ALL"
]
ignore = [
   "CPY",     # ignore missing-copyright-notice
   "RET504",  # ignore assigning right before returning
   "T20",     # ignore print statements
]

[lint.pylint]
max-locals = 15
max-args = 5

[lint.pydocstyle]
convention = "google"