preview = true
line-length = 120

[lint]
select = [
   "ALL"
]
ignore = [
   "missing-copyright-notice",
   "print",
   "p-print",
   "unnecessary-assign",
]

[lint.pylint]
max-locals = 15
max-args = 5

[lint.pydocstyle]
convention = "google"