preview = true
line-length = 120

[lint]
select = [
   "ALL"
]
ignore = [
   "CPY",     # ignore warning for missing copyright notice
   "RET504",  # ignore warning for assigning right before returning
   "T20",     # ignore warning for using print statements
]

[lint.pylint]
max-locals = 15
max-args = 5

[lint.pydocstyle]
convention = "google"